# Generated by Django 5.1.2 on 2024-10-29 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20241025_0239'),
    ]

    operations = [
    ]
